import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def login_as_user(driver):
    driver.get("http://localhost:3000/login")
    
    email_input = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//input[@type='email']"))
    )
    password_input = driver.find_element(By.XPATH, "//input[@type='password']")
    submit_btn = driver.find_element(By.XPATH, "//button[@type='submit']")
    
    email_input.send_keys("jagannathsyam2000@gmail.com")
    password_input.send_keys("test")
    submit_btn.click()
    
    WebDriverWait(driver, 10).until(
        EC.url_contains("/dashboard")
    )

def test_user_dashboard_tabs_navigation(driver):
    """
    [ROLE: Standard User]
    OBJECTIVE: Validate sidebar navigation across user portal sections.
    PRECONDITIONS: Logged in as Standard User (jagannathsyam2000@gmail.com).
    STEPS:
      1. Click 'My Cases' tab.
      2. Click 'Reports' tab.
      3. Click 'Profile' tab.
      4. Click 'Settings' tab.
    EXPECTED RESULT: View updates smoothly for all user sidebar tabs.
    """
    login_as_user(driver)
    
    # Verify we are on Dashboard
    assert "/dashboard" in driver.current_url
    
    # Check for sidebar tabs: "My Cases", "Reports", "Profile", "Settings"
    tabs = ["My Cases", "Reports", "Profile", "Settings"]
    for tab_name in tabs:
        tab_btn = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, f"//button[contains(., '{tab_name}')] | //a[contains(., '{tab_name}')]"))
        )
        tab_btn.click()
        time.sleep(1)
        assert tab_name in driver.page_source or "Cases" in driver.page_source or "Profile" in driver.page_source

def test_user_create_new_case(driver):
    """
    [ROLE: Standard User]
    OBJECTIVE: Verify end-to-end Case Creation flow for Standard User.
    PRECONDITIONS: Logged in as Standard User.
    STEPS:
      1. Navigate to 'My Cases'.
      2. Click 'New Case' button to trigger modal.
      3. Enter automated case title and description in form.
      4. Submit case creation form.
    EXPECTED RESULT: Case creation modal closes and newly created case appears in case list.
    """
    login_as_user(driver)
    
    # Navigate to My Cases tab
    my_cases_btn = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'My Cases')] | //a[contains(., 'My Cases')]"))
    )
    my_cases_btn.click()
    
    # Click "New Case" button
    new_case_btn = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'New Case')]"))
    )
    new_case_btn.click()
    
    # Wait for modal
    modal_title = WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.XPATH, "//h3[text()='Create Case File']"))
    )
    assert modal_title.is_displayed()
    
    # Fill in case title & description
    title_input = driver.find_element(By.XPATH, "//input[@placeholder='e.g. Presidential campaign audio swap leak']")
    desc_input = driver.find_element(By.XPATH, "//textarea[@placeholder='Specify brief case description for forensic context...']")
    
    case_name = f"Test Case Automated {int(time.time())}"
    title_input.send_keys(case_name)
    desc_input.send_keys("Automated test case description generated by Selenium runner.")
    
    # Submit form
    submit_btn = driver.find_element(By.XPATH, "//button[@type='submit' and contains(text(), 'Create Case')]")
    submit_btn.click()
    
    # Wait for modal to close / case list to update
    time.sleep(2)
    
    # Verify case appears in page source or DOM
    assert case_name in driver.page_source or "Case File" in driver.page_source or "Case #" in driver.page_source

def test_user_reports_page_ui(driver):
    """
    [ROLE: Standard User]
    OBJECTIVE: Validate Reports section UI layout and filters.
    PRECONDITIONS: Logged in as Standard User.
    STEPS:
      1. Click 'Reports' sidebar tab.
      2. Verify reports table and search filter controls appear.
    EXPECTED RESULT: Reports section renders without issues.
    """
    login_as_user(driver)
    
    # Click on Reports
    reports_tab = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.XPATH, "//button[contains(., 'Reports')] | //a[contains(., 'Reports')]"))
    )
    reports_tab.click()
    
    # Verify Reports section elements
    reports_heading = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.XPATH, "//*[contains(text(), 'Reports') or contains(text(), 'Generated')]"))
    )
    assert reports_heading.is_displayed()
