"""remove_verification_fields

Revision ID: 17da8177d588
Revises: 7d99197069ac
Create Date: 2026-08-04 00:06:02.570858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17da8177d588'
down_revision: Union[str, Sequence[str], None] = '7d99197069ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('investigator_profiles_ibfk_2'), 'investigator_profiles', type_='foreignkey')
    op.drop_column('investigator_profiles', 'rejection_reason')
    op.drop_column('investigator_profiles', 'approved_at')
    op.drop_column('investigator_profiles', 'verification_status')
    op.drop_column('investigator_profiles', 'approved_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigator_profiles', sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('investigator_profiles', sa.Column('verification_status', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('investigator_profiles', sa.Column('approved_at', mysql.DATETIME(), nullable=True))
    op.add_column('investigator_profiles', sa.Column('rejection_reason', mysql.VARCHAR(length=500), nullable=True))
    op.create_foreign_key(op.f('investigator_profiles_ibfk_2'), 'investigator_profiles', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
