"""Add InvitationLog and upgrade InvestigatorInvitation

Revision ID: 7d99197069ac
Revises: 9a19bc6db248
Create Date: 2026-08-03 23:31:00.141007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d99197069ac'
down_revision: Union[str, Sequence[str], None] = '9a19bc6db248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['investigator_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_logs_id'), 'invitation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_logs_invitation_id'), 'invitation_logs', ['invitation_id'], unique=False)
    op.add_column('investigator_invitations', sa.Column('invitation_type', sa.String(length=50), nullable=False))
    op.add_column('investigator_invitations', sa.Column('delivery_status', sa.String(length=50), nullable=False))
    op.add_column('investigator_invitations', sa.Column('send_attempts', sa.Integer(), nullable=False))
    op.add_column('investigator_invitations', sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('investigator_invitations', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigator_invitations', 'accepted_at')
    op.drop_column('investigator_invitations', 'last_attempt_at')
    op.drop_column('investigator_invitations', 'send_attempts')
    op.drop_column('investigator_invitations', 'delivery_status')
    op.drop_column('investigator_invitations', 'invitation_type')
    op.drop_index(op.f('ix_invitation_logs_invitation_id'), table_name='invitation_logs')
    op.drop_index(op.f('ix_invitation_logs_id'), table_name='invitation_logs')
    op.drop_table('invitation_logs')
    # ### end Alembic commands ###
